### ISSUE TITLE
Comments by logged out users

### ISSUE THREAD

**Issue by slaFFik** [kagg-design/kagg-fast-post-generator#12]
Right now all the generated comments are for the users that exist on a site.
It would be super handy if it was possible to allow comments generated by site visitors not users (so basically by logged out users).
Maybe even define the % (so by setting 10% - this number of comments will be generated by logged in users, everything else - by logged-out users).

**Comment by kagg-design** [comment]
Done in this commit: d669addada5481c24f2f3e6eb44ea898f50c1919.
