### ISSUE TITLE
Randomize dates

### ISSUE THREAD

**Issue by slaFFik** [kagg-design/kagg-fast-post-generator#13]
I created a site, generated 100 posts, 20 users and 1000 comments.
So everything was generated in December 2021 and December 2022.

Here is an example for comments: 
<img width="648" alt="image" src="https://user-images.githubusercontent.com/282234/206573801-4258ef96-09ea-4d79-8ae3-22bb7d2da634.png">

All comments were generated either today, or a year ago on 2021/12/13.

Posts:
<img width="364" alt="image" src="https://user-images.githubusercontent.com/282234/206573861-ef250979-78ff-4ed1-a28d-4d105dcf5d72.png">

It would really nice if the posts/comments could be spread across the past year, for example.

**Comment by kagg-design** [comment]
It was not an easy task. Done for posts, users, and comments: https://github.com/kagg-design/kagg-fast-post-generator/commit/3de4888412333b167d29a90c7ca2bc4c207a5b11

**Comment by slaFFik** [comment]
Thank you! Looking forward for the public release :)
