### ISSUE TITLE
If mysql user can't read CSV-file the plugin doesn't handle such situation

### ISSUE THREAD

**Issue by versusbassz** [kagg-design/kagg-fast-post-generator#2]
![Screenshot_2022-03-31_15-44-19](https://user-images.githubusercontent.com/2342074/161065736-9f7b1beb-2621-45a1-addd-45dcd43229c3.png)

**Comment by kagg-design** [comment]
Fixed in 7d7bf5a6c7149a095bd8304dc4e368562fd5b76f.
