### ISSUE TITLE
unable to activate

### ISSUE THREAD

**Issue by lmwp** [kagg-design/kagg-fast-post-generator#6]
When I try to activate your extension I've a fatal :
```
( ! ) Warning: require_once(/home/csn/Local Sites/wp59/app/public/wp-content/plugins/kagg-fast-post-generator-old/vendor/autoload.php): failed to open stream: No such file or directory in /home/csn/Local Sites/wp59/app/public/wp-content/plugins/kagg-fast-post-generator-old/plugin.php on line 59
Call Stack
#	Time	Memory	Function	Location
1	0.0002	369424	{main}( )	.../plugins.php:0
2	0.2076	14231576	plugin_sandbox_scrape( $plugin = 'kagg-fast-post-generator-old/plugin.php' )	.../plugins.php:192
3	0.2077	14231904	include_once( '/home/csn/Local Sites/wp59/app/public/wp-content/plugins/kagg-fast-post-generator-old/plugin.php )	.../plugin.php:2288

( ! ) Fatal error: require_once(): Failed opening required '/home/csn/Local Sites/wp59/app/public/wp-content/plugins/kagg-fast-post-generator-old/vendor/autoload.php' (include_path='.:/usr/share/php:/www/wp-content/pear') in /home/csn/Local Sites/wp59/app/public/wp-content/plugins/kagg-fast-post-generator-old/plugin.php on line 59
Call Stack
#	Time	Memory	Function	Location
1	0.0002	369424	{main}( )	.../plugins.php:0
2	0.2076	14231576	plugin_sandbox_scrape( $plugin = 'kagg-fast-post-generator-old/plugin.php' )	.../plugins.php:192
3	0.2077	14231904	include_once( '/home/csn/Local Sites/wp59/app/public/wp-content/plugins/kagg-fast-post-generator-old/plugin.php )	.../plugin.php:2288

```
It seem that **vendor/autoload.php** does not exist

Thank you

**Comment by kagg-design** [comment]
Of course. You have to run `composer install` before usage.

**Comment by lmwp** [comment]
Sorry but I still can't activate it. In fact I had launched compose but there was a problem with the generation. Now the error is :
`( ! ) Fatal error: Uncaught Error: Class 'KAGG\Generator\Main' not found in /home/csn/Local Sites/wp59/app/public/wp-content/plugins/kagg-fast-post-generator/plugin.php on line 61
( ! ) Error: Class 'KAGG\Generator\Main' not found in /home/csn/Local Sites/wp59/app/public/wp-content/plugins/kagg-fast-post-generator/plugin.php on line 61
Call Stack
#	Time	Memory	Function	Location
1	0.0002	369392	{main}( )	.../plugins.php:0
2	0.2330	14242272	plugin_sandbox_scrape( $plugin = 'kagg-fast-post-generator/plugin.php' )	.../plugins.php:192
3	0.2330	14242584	include_once( '/home/csn/Local Sites/wp59/app/public/wp-content/plugins/kagg-fast-post-generator/plugin.php )	.../plugin.php:2288
`
Composer is ok on my side and the files generated. I work locally with Locale Ubuntu version. PHP7.4.1 (same problem in 8.0) / Apache 2.4.43 PHP SAPI = fpm-fcgi which runs WordPress 5.9.3. 
If you need more I am at your disposal

**Comment by kagg-design** [comment]
`Composer install` is a simple command. If it does not work for you, something is definitely wrong in your environment.

From now on, you can download the plugin directly from the official WordPress repository: https://wordpress.org/plugins/kagg-fast-post-generator/
