### ISSUE TITLE
Make `mysqli.allow_local_infile` warning persistent

### ISSUE THREAD

**Issue by cadic** [kagg-design/kagg-fast-post-generator#7]
When the plugin is activated for the first time, it will check for `allow_local_infile` setting is On.

On a page reload the warning is gone. This is causing couple problems:

1. Low experienced site owner may be confused because they could not remember the setting name if they want to send it to server/hosting tech support.
2. Someone might think they did perform the correct configuration and the warning isn't displayed any more because everything is ok (while it's still not ok)

Could we keep the warning visible until the `mysqli.allow_local_infile` is properly set up? It doesn't look redundant since the plugin could not operate normally before that at all.

**Comment by cadic** [comment]
It's still possible to refresh the warning by disabling/enabling the plugin again, but will be much better just to display the warning until fixed.

**Comment by kagg-design** [comment]
Thank you, Max!

Fixed in 4d0c935.
